[package]
name = "aigis"
description = "A simple and configurable content proxy."
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[features]
default = ["rustls-tls", "cache-moka"]
# TLS Backends
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
# Caching Backends
cache-moka = ["http-cache-reqwest", "http-cache-reqwest/manager-moka"]

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
axum = { version = "0.7.4", features = ["http2", "tracing"] }
bytes = "1.5.0"
dotenvy = "0.15.7"
http-cache-reqwest = { version = "0.13.0", optional = true, default-features = false }
image = "0.25.0"
mime = "0.3.17"
reqwest = { version = "0.11.27", default-features = false } # TODO: Enable "macos-sytem-configuration" and "charset" when upgrading to 0.12
reqwest-middleware = { version = "0.2.5" }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tower-http = { version = "0.5.2", features = [
    "catch-panic",
    "normalize-path",
    "timeout",
    "trace",
] }
tracing = "0.1.40"
url = "2.5.0"

[lints.rust]
missing_docs = "warn"

[lints.rustdoc]
missing_crate_level_docs = "warn"
unescaped_backticks = "warn"
